esphome:
  name: auto-watering-system-1

esp8266:
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.176
    gateway: 192.168.1.1
    subnet: 255.255.255.0
  fast_connect: true
  output_power: 17.0

ota:
  - platform: esphome
    password: !secret ota_password

api:
  password: !secret api_password

logger:
  level: DEBUG

# Датчик влажности (емкостной)
sensor:
  - platform: adc
    pin: A0  # Подключён к емкостному датчику
    name: "Влажность почвы (сырое значение)"
    id: soil_moisture_raw
    update_interval: 60s
    filters:
      - multiply: 3.3
      - median:
          window_size: 3
          send_every: 1

  # Переводим в проценты (калибровка)
  - platform: template
    name: "Влажность почвы (%)"
    id: soil_moisture_percent
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: 60s
    lambda: |-
      float raw = id(soil_moisture_raw).state;
      // Пример калибровки (заменить на свои значения!)
      // 0% = 3.3 В (сухая почва)
      // 100% = 1.6 В (влажная почва)
      float dry_voltage = 2.57;  // ← Заменить на своё значение (сухая почва)
      float wet_voltage = 0.93;  // ← Заменить на своё значение (влажная почва)

      if (raw >= dry_voltage) return 0.0;
      if (raw <= wet_voltage) return 100.0;

      float moisture = 100.0 - ((raw - wet_voltage) / (dry_voltage - wet_voltage)) * 100.0;
      if (moisture < 0) moisture = 0;
      if (moisture > 100) moisture = 100;
      return moisture;

# Переключатель: включить насос (команда из HA)
switch:
  - platform: gpio
    pin: GPIO5  # ← Пин, к которому подключён MOSFET (gate)
    name: "Полить цветок"
    id: water_flower_switch
    restore_mode: ALWAYS_OFF  # Не включать при перезагрузке

# Скрипт: включить насос на 5 секунд
script:
  - id: water_for_5_seconds
    then:
      - switch.turn_on: water_flower_switch
      - delay: 5s
      - switch.turn_off: water_flower_switch

# Управление: при получении команды "ON" — запустить скрипт
binary_sensor:
  - platform: template
    name: "Команда полить цветок"
    id: water_command
    on_press:
      - script.execute: water_for_5_seconds  # Выполнить полив на 5 секунд
      
button:
  - platform: template
    name: "Полить цветок"
    id: water_flower_button
    on_press:
      - script.execute: water_for_5_seconds  # Выполнить полив на 5 секунд
