esphome:
  name: garage-car-evgen
  # Уникальное имя устройства

esp8266:
  board: d1_mini  # Замени на свою модель, если не D1 Mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.172
    gateway: 192.168.1.1
    subnet: 255.255.255.0
  fast_connect: true
  output_power: 17.0  # Можно уменьшить, если сигнал сильный

ota:
  - platform: esphome
    password: !secret ota_password

api:
  password: !secret api_password

logger:
  level: DEBUG

# Подключение HC-SR04
# VCC -> 5V
# GND -> GND
# Trig -> D6 (GPIO12)
# Echo -> D7 (GPIO13)

# Правильный синтаксис для датчика HC-SR04
sensor:
  # Сенсор расстояния
  - platform: ultrasonic
    trigger_pin: D6  # GPIO12 на D1 Mini
    echo_pin: D7     # GPIO13 на D1 Mini
    name: "Расстояние до автомобиля"
    id: car_distance_raw  # ID для использования в других компонентах
    unit_of_measurement: "m"
    accuracy_decimals: 2
    update_interval: 5s  # Частота измерения
    filters:
      - median: # Усреднение для стабильности
          window_size: 3
          send_every: 1

binary_sensor:
  # Бинарный сенсор: присутствие автомобиля
  - platform: template
    name: "Автомобиль в гараже"
    id: car_present
    device_class: occupancy
    filters:
      # Задержка, чтобы избежать "дребезга"
      - delayed_on: 2s       # Автомобиль считается припаркованным, если в зоне > 2 сек
      - delayed_off: 5s      # Автомобиль считается уехавшим, если вне зоны > 5 сек
    lambda: |-
      // Условие: если расстояние до объекта меньше порога — значит, автомобиль на месте
      const float threshold = 0.9; // Порог в метрах. Настрой под свою парковку!
      if (isnan(id(car_distance_raw).state)) {
        return false; // Если датчик не отвечает — считаем, что нет автомобиля
      }
      return id(car_distance_raw).state < threshold;

# Включаем светодиод на GPIO2, когда автомобиль обнаружен
interval:
  - interval: 1s  # Проверяем каждую секунду
    then:
      - if:
          condition:
            binary_sensor.is_on: car_present  # Если автомобиль в гараже
          then:
            - output.turn_on: led_gpio2_out
          else:
            - output.turn_off: led_gpio2_out

# Управляем GPIO2 напрямую как output
output:
  - platform: gpio
    pin:
      number: D4  # GPIO2 на D1 Mini (встроенный светодиод)
      inverted: true  # Если светодиод включается при LOW (для встроенного D4 обычно НЕТ)
    id: led_gpio2_out
